apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Values.name }}-ingress"
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: "{{ .Values.name }}-service"
          port: 80