apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gitlab
  ports:
    - name: http       # 🔹 nombre obligatorio y único
      port: 80
      targetPort: 80

  type: ClusterIP