apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{.Values.name}}-config-pvc"
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "{{.Values.name}}-config-pv"

