apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{.Values.name}}-config-pv"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path # ✅ agregar
  hostPath:
    path: "/mnt/{{.Values.name}}"
