{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}

  labels:
    namespace: {{ .Values.namespace }}
    repo: {{ .Values.name }}

    environment: {{ .Values.metadata.environment }}
    owner: {{ .Values.metadata.owner }}
    commit: {{ .Values.metadata.commit }}

spec:
  replicas: 1
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      stableService: {{ .Values.name }}-svc
      canaryService: {{ .Values.name }}-canary-svc

      # trafficRouting:
      #   traefik:
      #     weightedTraefikServiceName: {{ .Values.name }}-ts

      #scaleDownDelaySeconds: 10
      steps:
      - setWeight: 1
      - pause: {}

      - setWeight: 30
      - pause:
          duration: 20s

      - setWeight: 40
      - pause:
          duration: 20s

      - setWeight: 60
      - pause:
          duration: 10s

      - setWeight: 100
  revisionHistoryLimit: 1
  
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}

    spec:
      imagePullSecrets:
      - name: ghcr-secret

      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.container.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.container.port }}

        volumeMounts:
        - name: env-file
          mountPath: /app/.env
          subPath: .env


        resources:
          requests:
            cpu: 100m
            memory: 258Mi

          limits:
            cpu: 600m
            memory: 556Mi

      volumes:
      - name: env-file
        configMap:
          name: {{ .Values.name }}-env-file

{{- end }}