apiVersion: traefik.io/v1alpha1
kind: TraefikService

metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    rollouts.argoproj.io/managed-by: {{ .Values.name }}
spec:
  weighted:
    services:

      - name: {{ .Values.name }}-svc
        port: {{ .Values.service.port }}

      # - name: {{ .Values.name }}-canary-svc
      #   port: {{ .Values.service.port }}